# Generated by Django 4.2.2 on 2023-07-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=40)),
                ('NPregunta', models.CharField(max_length=10)),
                ('Respuesta', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomProyecto', models.CharField(max_length=40)),
                ('DesProyecto', models.CharField(max_length=500)),
                ('TipoProyecto', models.CharField(choices=[('Escritorio', 'Escritorio'), ('App', 'Aplicacion'), ('Juego', 'Juegos')], default='Escritorio', max_length=10)),
                ('imgsProyecto', models.ImageField(upload_to='', verbose_name='ImagenDelProyecto')),
                ('LinkProyecto', models.CharField(max_length=400)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.usuario')),
            ],
        ),
    ]
