# Generated by Django 4.2.2 on 2023-07-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario',
            new_name='NomUsuario',
        ),
    ]
